M48
; DRILL file KiCad 10.0.6 date 2026-09-21T21:34:22
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-21T21:34:22-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X110.617Y-51.359
X110.693Y-142.443
X197.815Y-51.359
X197.815Y-142.443
M30
